# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Community Codes
email: smtxcommunitycodes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We're a community of learners interested in improving our web development skills through free workshops on the 2nd Tuesday of each month!.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://communitycodes.org" # the base hostname & protocol for your site
twitter_username: communitycodes
github_username:  communitycodes

# Build settings
markdown: kramdown
